version: '3'
services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    environment:
      DATABASE_URL: "mysql2://root:@db:3306/app_development"
    volumes:
      - ".:/app"
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: ["bundle", "exec", "rails", "s", "-b", "0.0.0.0"]
  db:
    image: "mysql:5.6"
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "app_development"
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql:
    driver: local
