# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "Hello" do
    optional :from, :string, 1
  end
end

Hello = Google::Protobuf::DescriptorPool.generated_pool.lookup("Hello").msgclass
